version: '3'

services:

  ldap:
    image: openldap
    ports:
      - "389:389"

  web:
    image: webappldap
    depends_on:
      - ldap
    labels:
        - "traefik.backend=ldap"
        - "traefik.frontend.rule=Host:127.0.0.1"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.port=80"

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
