version: '3'

services:

  ldap:
    image: openldap
    #container_name: openldap1
    ports:
      - "389:389"
    dns: docker.ldap.com

  web:
    image: webappldap
    #container_name: webappldap1
    ports:
     - "80:80"
    depends_on:
      - ldap
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
